version: '3.3'
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'mysql'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        restart: always
        links:
            - db
        ports:
            - 8082:80
        environment:
            - PMA_ARBITRARY=1
volumes:
    my-db: